CREATE TABLE `abm_account` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `account_name` varchar(255) NOT NULL,
  `domain` varchar(255) NOT NULL,
  `icp_tier` varchar(20) DEFAULT NULL,
  `engagement_score` int(11) DEFAULT NULL,
  `total_visits` int(11) DEFAULT NULL,
  `total_page_views` int(11) DEFAULT NULL,
  `first_seen_at` datetime DEFAULT NULL,
  `last_activity_at` datetime DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_EEBF221AA7A91E0B` (`domain`),
  KEY `IDX_EEBF221A979B1AD6` (`company_id`),
  KEY `idx_abm_domain` (`domain`),
  KEY `idx_abm_icp_tier` (`icp_tier`),
  KEY `idx_abm_engagement` (`engagement_score`),
  CONSTRAINT `FK_EEBF221A979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `abm_hits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `abm_account_id` int(11) DEFAULT NULL,
  `timestamp` datetime NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `organization_name` varchar(255) DEFAULT NULL,
  `url_visited` longtext DEFAULT NULL,
  `session_duration` int(11) DEFAULT NULL,
  `page_views` int(11) DEFAULT NULL,
  `firmographic_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`firmographic_data`)),
  `is_identified` tinyint(1) NOT NULL,
  `playbook_triggered` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_50A8D529979B1AD6` (`company_id`),
  KEY `IDX_50A8D5298B9C0B45` (`abm_account_id`),
  KEY `idx_company_timestamp` (`company_id`,`timestamp`),
  CONSTRAINT `FK_50A8D5298B9C0B45` FOREIGN KEY (`abm_account_id`) REFERENCES `abm_account` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_50A8D529979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `activities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `type` varchar(50) NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `outcome` varchar(50) DEFAULT NULL,
  `outcome_detail` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `duration_minutes` int(11) DEFAULT NULL,
  `activity_date` datetime NOT NULL,
  `follow_up_date` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_B5F1AFE5E7A1254A` (`contact_id`),
  KEY `IDX_B5F1AFE5A76ED395` (`user_id`),
  KEY `idx_activities_user_date` (`user_id`,`activity_date`),
  KEY `idx_activities_company` (`company_id`),
  CONSTRAINT `FK_B5F1AFE5979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_B5F1AFE5A76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_B5F1AFE5E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `asm_curves` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `component_count_min` int(11) NOT NULL,
  `component_count_max` int(11) DEFAULT NULL,
  `cost_per_unit` decimal(15,4) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `asof` datetime NOT NULL,
  `version_id` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_component_count_asof` (`component_count_min`,`asof`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `entity_type` varchar(100) NOT NULL,
  `entity_id` int(11) NOT NULL,
  `action` varchar(50) NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `old_values` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`old_values`)),
  `new_values` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`new_values`)),
  `changed_fields` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`changed_fields`)),
  `created_at` datetime NOT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_entity` (`entity_type`,`entity_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `FK_D62F2858A76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `bandit_arms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `arm_type` varchar(50) NOT NULL,
  `arm_name` varchar(255) NOT NULL,
  `arm_value` longtext NOT NULL,
  `alpha` double NOT NULL DEFAULT 1,
  `beta` double NOT NULL DEFAULT 1,
  `icp_cluster` varchar(100) NOT NULL DEFAULT 'global',
  `recent_negative_rate` double NOT NULL DEFAULT 0,
  `quarantined` tinyint(1) NOT NULL DEFAULT 0,
  `is_control` tinyint(1) NOT NULL DEFAULT 0,
  `total_trials` int(11) NOT NULL DEFAULT 0,
  `total_successes` int(11) NOT NULL DEFAULT 0,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `last_used_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_bandit_arm_type` (`arm_type`),
  KEY `idx_bandit_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `bom_lines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote_id` int(11) NOT NULL,
  `line_number` int(11) NOT NULL,
  `mpn` varchar(255) DEFAULT NULL,
  `original_mpn` varchar(255) DEFAULT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `matched_mpn` varchar(255) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `bom_description` longtext DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(10,4) DEFAULT NULL,
  `extended_price` decimal(12,2) DEFAULT NULL,
  `procurement_source` varchar(50) DEFAULT NULL,
  `has_exception` tinyint(1) DEFAULT NULL,
  `exception_reason` varchar(100) DEFAULT NULL,
  `lead_time_days` int(11) DEFAULT NULL,
  `availability` varchar(20) DEFAULT NULL,
  `confidence_score` smallint(6) DEFAULT NULL,
  `confidence_level` varchar(20) DEFAULT NULL,
  `confidence_reasons` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`confidence_reasons`)),
  `confidence_warnings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`confidence_warnings`)),
  `requires_review` tinyint(1) DEFAULT NULL,
  `manually_verified` tinyint(1) DEFAULT NULL,
  `manual_unit_price` decimal(10,4) DEFAULT NULL,
  `manual_notes` longtext DEFAULT NULL,
  `verified_by` varchar(100) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `lifecycle_status` varchar(50) DEFAULT NULL,
  `lifecycle_warning` varchar(20) DEFAULT NULL,
  `price_source_url` varchar(500) DEFAULT NULL,
  `alternative_parts` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`alternative_parts`)),
  `distributor_search_url` varchar(500) DEFAULT NULL,
  `supplier_name` varchar(255) DEFAULT NULL,
  `supplier_product_url` varchar(500) DEFAULT NULL,
  `sourcing_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sourcing_data`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_bom_quote` (`quote_id`),
  KEY `idx_bom_mpn` (`mpn`),
  KEY `idx_bom_review` (`requires_review`),
  CONSTRAINT `FK_3CDE317DB805178` FOREIGN KEY (`quote_id`) REFERENCES `quotes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `calendar_event_attendees` (
  `user_id` int(11) NOT NULL,
  `calendar_event_id` int(11) NOT NULL,
  PRIMARY KEY (`user_id`,`calendar_event_id`),
  KEY `IDX_258586B3A76ED395` (`user_id`),
  KEY `IDX_258586B37495C8E3` (`calendar_event_id`),
  CONSTRAINT `FK_258586B37495C8E3` FOREIGN KEY (`calendar_event_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_258586B3A76ED395` FOREIGN KEY (`user_id`) REFERENCES `calendar_events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `calendar_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_event_id` int(11) DEFAULT NULL,
  `organizer_id` int(11) NOT NULL,
  `company_id` int(11) DEFAULT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `lead_id` int(11) DEFAULT NULL,
  `rfq_id` int(11) DEFAULT NULL,
  `task_id` int(11) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `event_type` varchar(50) NOT NULL,
  `start_at` datetime NOT NULL,
  `end_at` datetime NOT NULL,
  `all_day` tinyint(1) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  `meeting_url` varchar(500) DEFAULT NULL,
  `visibility` varchar(20) NOT NULL,
  `status` varchar(20) NOT NULL,
  `color` varchar(7) DEFAULT NULL,
  `is_recurring` tinyint(1) NOT NULL,
  `recurring_frequency` varchar(20) DEFAULT NULL,
  `recurring_until` date DEFAULT NULL,
  `recurring_count` int(11) DEFAULT NULL,
  `recurring_days` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`recurring_days`)),
  `reminder_minutes` int(11) DEFAULT NULL,
  `reminder_sent` tinyint(1) NOT NULL,
  `external_id` varchar(255) DEFAULT NULL,
  `external_provider` varchar(50) DEFAULT NULL,
  `last_synced_at` datetime DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_F9E14F168DB60186` (`task_id`),
  KEY `IDX_F9E14F16EE3A445A` (`parent_event_id`),
  KEY `IDX_F9E14F16979B1AD6` (`company_id`),
  KEY `IDX_F9E14F16E7A1254A` (`contact_id`),
  KEY `IDX_F9E14F1655458D` (`lead_id`),
  KEY `IDX_F9E14F16ABD9545F` (`rfq_id`),
  KEY `idx_calendar_start` (`start_at`),
  KEY `idx_calendar_end` (`end_at`),
  KEY `idx_calendar_type` (`event_type`),
  KEY `idx_calendar_organizer` (`organizer_id`),
  CONSTRAINT `FK_F9E14F1655458D` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_F9E14F16876C4DDA` FOREIGN KEY (`organizer_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_F9E14F168DB60186` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_F9E14F16979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_F9E14F16ABD9545F` FOREIGN KEY (`rfq_id`) REFERENCES `rfqs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_F9E14F16E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_F9E14F16EE3A445A` FOREIGN KEY (`parent_event_id`) REFERENCES `calendar_events` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `capacity_calendars` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `production_date` date NOT NULL,
  `available_slots` int(11) NOT NULL,
  `booked_slots` int(11) NOT NULL,
  `is_holiday` tinyint(1) NOT NULL,
  `holiday_name` longtext DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_production_date` (`production_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `case_studies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `sector` varchar(100) NOT NULL,
  `challenge` longtext DEFAULT NULL,
  `solution` longtext DEFAULT NULL,
  `results` longtext DEFAULT NULL,
  `published` tinyint(1) NOT NULL DEFAULT 0,
  `anonymized` tinyint(1) NOT NULL DEFAULT 0,
  `language` varchar(5) NOT NULL,
  `pdf_path` varchar(500) DEFAULT NULL,
  `published_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_6C0AEF34979B1AD6` (`company_id`),
  CONSTRAINT `FK_6C0AEF34979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `companies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `sector` varchar(100) DEFAULT NULL,
  `account_tier` varchar(10) NOT NULL,
  `region` varchar(100) DEFAULT NULL,
  `pipeline_stage` varchar(50) NOT NULL,
  `company_status` varchar(30) NOT NULL DEFAULT 'approved',
  `website` varchar(2048) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `linked_in_url` varchar(2048) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `physical_site` varchar(255) DEFAULT NULL,
  `linkedin_company_url` varchar(500) DEFAULT NULL,
  `source_notes` longtext DEFAULT NULL,
  `legal_name` varchar(255) DEFAULT NULL,
  `google_drive_link` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_company_name` (`name`),
  KEY `idx_company_sector` (`sector`),
  KEY `idx_company_pipeline` (`pipeline_stage`),
  KEY `idx_company_status` (`company_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `company_canonicals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `domain` varchar(255) NOT NULL,
  `alias` varchar(255) DEFAULT NULL,
  `is_primary` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_domain` (`domain`),
  KEY `idx_company_id` (`company_id`),
  CONSTRAINT `FK_514DA330979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `competitor_detection` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lead_id` int(11) NOT NULL,
  `competitor_domain` varchar(255) NOT NULL,
  `competitor_name` varchar(255) NOT NULL,
  `competitor_tier` smallint(6) NOT NULL,
  `detected_in` varchar(100) NOT NULL,
  `detection_confidence` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_18EA4AA355458D` (`lead_id`),
  KEY `idx_competitor_domain` (`competitor_domain`),
  CONSTRAINT `FK_18EA4AA355458D` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `compliance_document_versions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `document_id` int(11) NOT NULL,
  `version_number` int(11) NOT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `uploaded_by` varchar(100) DEFAULT NULL,
  `uploaded_at` datetime NOT NULL,
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `rejection_reason` longtext DEFAULT NULL,
  `is_current` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `IDX_A53B08EFC33F7837` (`document_id`),
  CONSTRAINT `FK_A53B08EFC33F7837` FOREIGN KEY (`document_id`) REFERENCES `compliance_documents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `compliance_documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `required` tinyint(1) NOT NULL,
  `provided` tinyint(1) NOT NULL,
  `status` varchar(100) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `uploaded_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `snoozed_until` date DEFAULT NULL,
  `snooze_reason` varchar(255) DEFAULT NULL,
  `snoozed_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_EABE6873979B1AD6` (`company_id`),
  CONSTRAINT `FK_EABE6873979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contact_email_campaigns` (
  `contact_id` int(11) NOT NULL,
  `email_campaign_id` int(11) NOT NULL,
  PRIMARY KEY (`contact_id`,`email_campaign_id`),
  KEY `IDX_776FD465E7A1254A` (`contact_id`),
  KEY `IDX_776FD465E0F98BC3` (`email_campaign_id`),
  CONSTRAINT `FK_776FD465E0F98BC3` FOREIGN KEY (`email_campaign_id`) REFERENCES `email_campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_776FD465E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `job_title` varchar(100) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `linked_in_url` varchar(2048) DEFAULT NULL,
  `source` varchar(50) DEFAULT NULL,
  `primary_contact` tinyint(1) NOT NULL DEFAULT 0,
  `notes` longtext DEFAULT NULL,
  `role` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_33401573979B1AD6` (`company_id`),
  KEY `idx_contact_email` (`email`),
  CONSTRAINT `FK_33401573979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `coo_supplier_decls` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_name` varchar(255) NOT NULL,
  `mpn` varchar(255) NOT NULL,
  `country_of_origin` varchar(2) NOT NULL,
  `hts_code` varchar(100) DEFAULT NULL,
  `evidence_url` longtext DEFAULT NULL,
  `declared_at` datetime NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  `certificate_number` varchar(100) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `is_verified` tinyint(1) NOT NULL,
  `verified_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_supplier_mpn` (`supplier_name`,`mpn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `custom_field_definitions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_by_id` int(11) DEFAULT NULL,
  `field_key` varchar(100) NOT NULL,
  `label` varchar(255) NOT NULL,
  `entity_type` varchar(50) NOT NULL,
  `field_type` varchar(50) NOT NULL,
  `description` longtext DEFAULT NULL,
  `placeholder` varchar(255) DEFAULT NULL,
  `default_value` varchar(255) DEFAULT NULL,
  `is_required` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `is_searchable` tinyint(1) NOT NULL,
  `show_in_list` tinyint(1) NOT NULL,
  `show_in_detail` tinyint(1) NOT NULL,
  `sort_order` int(11) NOT NULL,
  `field_group` varchar(100) DEFAULT NULL,
  `validation_rules` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`validation_rules`)),
  `options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`options`)),
  `config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`config`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_field_entity` (`field_key`,`entity_type`),
  KEY `IDX_A4967298B03A8386` (`created_by_id`),
  KEY `idx_custom_field_entity` (`entity_type`),
  CONSTRAINT `FK_A4967298B03A8386` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `custom_field_values` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `field_definition_id` int(11) NOT NULL,
  `entity_type` varchar(50) NOT NULL,
  `entity_id` int(11) NOT NULL,
  `text_value` longtext DEFAULT NULL,
  `number_value` decimal(20,6) DEFAULT NULL,
  `date_value` date DEFAULT NULL,
  `datetime_value` datetime DEFAULT NULL,
  `boolean_value` tinyint(1) DEFAULT NULL,
  `json_value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`json_value`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_field_value` (`field_definition_id`,`entity_type`,`entity_id`),
  KEY `IDX_6B64D7FF4D0FDD48` (`field_definition_id`),
  KEY `idx_custom_value_entity` (`entity_type`,`entity_id`),
  CONSTRAINT `FK_6B64D7FF4D0FDD48` FOREIGN KEY (`field_definition_id`) REFERENCES `custom_field_definitions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dataset_version` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dataset_type` varchar(100) NOT NULL,
  `version_uuid` varchar(36) NOT NULL,
  `sha256_hash` varchar(64) NOT NULL,
  `record_count` int(11) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `imported_at` datetime NOT NULL,
  `imported_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_94CEFF85606F4CA2` (`version_uuid`),
  KEY `idx_dataset_type` (`dataset_type`),
  KEY `idx_dataset_active` (`is_active`),
  KEY `idx_dataset_uuid` (`version_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dfm_finding` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote_id` int(11) NOT NULL,
  `dfm_rule_id` int(11) DEFAULT NULL,
  `finding_type` varchar(100) NOT NULL,
  `severity` varchar(20) NOT NULL,
  `description` longtext DEFAULT NULL,
  `remediation` longtext DEFAULT NULL,
  `cost_impact` decimal(10,2) DEFAULT NULL,
  `lead_time_impact` int(11) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_4C2C6BB09F7B7BD7` (`dfm_rule_id`),
  KEY `idx_dfm_quote` (`quote_id`),
  KEY `idx_dfm_severity` (`severity`),
  CONSTRAINT `FK_4C2C6BB09F7B7BD7` FOREIGN KEY (`dfm_rule_id`) REFERENCES `dfm_rules` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_4C2C6BB0DB805178` FOREIGN KEY (`quote_id`) REFERENCES `quotes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dfm_rules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rule_type` varchar(100) NOT NULL,
  `rule_name` varchar(255) NOT NULL,
  `severity` varchar(50) NOT NULL,
  `description` longtext DEFAULT NULL,
  `remediation_text` longtext DEFAULT NULL,
  `check_logic` longtext DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_rule_type_severity` (`rule_type`,`severity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
  `version` varchar(191) NOT NULL,
  `executed_at` datetime DEFAULT NULL,
  `execution_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
CREATE TABLE `email_campaigns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_id` int(11) DEFAULT NULL,
  `segment_id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `language` varchar(10) NOT NULL,
  `description` longtext DEFAULT NULL,
  `touch_count` int(11) NOT NULL,
  `touch_templates` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`touch_templates`)),
  `ab_test_variants` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`ab_test_variants`)),
  `active` tinyint(1) NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `from_name` varchar(255) DEFAULT NULL,
  `from_email` varchar(255) DEFAULT NULL,
  `body_html` longtext DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `type` varchar(20) DEFAULT NULL,
  `trigger_type` varchar(50) DEFAULT NULL,
  `trigger_conditions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`trigger_conditions`)),
  `send_time_optimization` tinyint(1) NOT NULL DEFAULT 0,
  `sent_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `scheduled_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_EC78EB5B5DA0FB8` (`template_id`),
  KEY `IDX_EC78EB5BDB296AAD` (`segment_id`),
  CONSTRAINT `FK_EC78EB5B5DA0FB8` FOREIGN KEY (`template_id`) REFERENCES `email_template` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_EC78EB5BDB296AAD` FOREIGN KEY (`segment_id`) REFERENCES `email_segment` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `email_segment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `filter_rules_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`filter_rules_json`)),
  `contact_count` int(11) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `last_calculated_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_segment_name` (`name`),
  KEY `idx_segment_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `email_sends` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `contact_id` int(11) NOT NULL,
  `touch_number` int(11) NOT NULL,
  `sent_at` datetime DEFAULT NULL,
  `opened` tinyint(1) NOT NULL DEFAULT 0,
  `clicked` tinyint(1) NOT NULL DEFAULT 0,
  `replied` tinyint(1) NOT NULL DEFAULT 0,
  `bounced` tinyint(1) NOT NULL DEFAULT 0,
  `variant` varchar(50) DEFAULT NULL,
  `email_address` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'queued',
  `scheduled_at` datetime DEFAULT NULL,
  `opened_at` datetime DEFAULT NULL,
  `clicked_at` datetime DEFAULT NULL,
  `retry_count` int(11) NOT NULL DEFAULT 0,
  `failure_reason` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_email_sends_campaign` (`campaign_id`),
  KEY `idx_email_sends_contact` (`contact_id`),
  CONSTRAINT `FK_633143B3E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_633143B3F639F774` FOREIGN KEY (`campaign_id`) REFERENCES `email_campaigns` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `email_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `subject_line` varchar(255) NOT NULL,
  `preview_text` varchar(255) DEFAULT NULL,
  `body_html` longtext NOT NULL,
  `body_text` longtext DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL,
  `personalization_tokens` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`personalization_tokens`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_template_name` (`name`),
  KEY `idx_template_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `email_unsubscribe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contact_id` int(11) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `reason` varchar(100) DEFAULT NULL,
  `feedback_text` longtext DEFAULT NULL,
  `unsubscribed_at` datetime NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_unsubscribe_contact` (`contact_id`),
  KEY `idx_unsubscribe_email` (`email`),
  CONSTRAINT `FK_B3AC4CB9E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `freight_tables` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `origin_port` varchar(100) NOT NULL,
  `destination_port` varchar(100) NOT NULL,
  `transport_mode` varchar(50) NOT NULL,
  `container_type` varchar(20) NOT NULL,
  `cost_per_unit` decimal(10,2) NOT NULL,
  `currency` varchar(10) NOT NULL,
  `transit_days` int(11) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `expiry_date` date DEFAULT NULL,
  `carrier` varchar(255) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `version_id` varchar(36) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_route` (`origin_port`,`destination_port`),
  KEY `idx_effective_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fta_rules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hs_code` varchar(20) NOT NULL,
  `fta_agreement` varchar(100) NOT NULL,
  `roo_requirement` longtext DEFAULT NULL,
  `roo_language` longtext DEFAULT NULL,
  `minimum_value_content` decimal(5,2) DEFAULT NULL,
  `requires_certificate` tinyint(1) NOT NULL,
  `certificate_type` varchar(50) DEFAULT NULL,
  `required_documents` longtext DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `effective_date` date NOT NULL,
  `expiry_date` date DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hs_code` (`hs_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fx_rates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from_currency` varchar(10) NOT NULL,
  `to_currency` varchar(10) NOT NULL,
  `rate` decimal(12,6) NOT NULL,
  `asof` datetime NOT NULL,
  `version_id` varchar(36) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_currencies` (`from_currency`,`to_currency`),
  KEY `idx_asof` (`asof`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hts_map_rules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(100) NOT NULL,
  `keywords` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`keywords`)),
  `hts_code` varchar(100) NOT NULL,
  `confidence` varchar(50) NOT NULL,
  `heuristic_logic` longtext DEFAULT NULL,
  `priority` int(11) NOT NULL,
  `notes` longtext DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_category_keywords` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `inbox_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `in_reply_to_id` int(11) DEFAULT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `from_email` varchar(255) NOT NULL,
  `subject` longtext DEFAULT NULL,
  `body_text` longtext DEFAULT NULL,
  `classification` varchar(30) DEFAULT NULL,
  `classification_confidence` decimal(5,2) DEFAULT NULL,
  `classification_method` varchar(30) DEFAULT NULL,
  `requires_human_review` tinyint(1) NOT NULL DEFAULT 0,
  `human_reviewed_at` datetime DEFAULT NULL,
  `reviewed_by` varchar(255) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `received_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_F635C51DDD92DAB8` (`in_reply_to_id`),
  KEY `IDX_F635C51DE7A1254A` (`contact_id`),
  KEY `idx_inbox_classification` (`classification`),
  KEY `idx_inbox_review` (`requires_human_review`),
  KEY `idx_inbox_from` (`from_email`),
  CONSTRAINT `FK_F635C51DDD92DAB8` FOREIGN KEY (`in_reply_to_id`) REFERENCES `outbound_messages` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_F635C51DE7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ip_maps` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `organization_name` varchar(255) DEFAULT NULL,
  `domain` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `country` varchar(2) DEFAULT NULL,
  `firmographic_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`firmographic_data`)),
  `asof` datetime NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ip_asof` (`ip_address`,`asof`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `leads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `company_name` varchar(255) NOT NULL,
  `legal_name` varchar(255) DEFAULT NULL,
  `website_root` varchar(255) DEFAULT NULL,
  `lead_url` varchar(500) DEFAULT NULL,
  `site_location` varchar(255) DEFAULT NULL,
  `us_state` varchar(10) DEFAULT NULL,
  `us_city_metro` varchar(100) DEFAULT NULL,
  `region_tag` varchar(50) DEFAULT NULL,
  `sector_tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sector_tags`)),
  `fit_signals` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`fit_signals`)),
  `morocco_signal` tinyint(1) DEFAULT NULL,
  `quality_stack` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`quality_stack`)),
  `contact_emails_public` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`contact_emails_public`)),
  `contact_form_url` varchar(500) DEFAULT NULL,
  `has_contact_form` tinyint(1) NOT NULL DEFAULT 0,
  `supplier_portal_url` varchar(500) DEFAULT NULL,
  `rfq_rfp_page_url` varchar(500) DEFAULT NULL,
  `supplier_portal_complexity` varchar(50) DEFAULT NULL,
  `defense_flag` tinyint(1) DEFAULT NULL,
  `last_seen` datetime DEFAULT NULL,
  `content_last_modified` datetime DEFAULT NULL,
  `lead_score` int(11) DEFAULT NULL,
  `notes_auto` longtext DEFAULT NULL,
  `dupe_key` varchar(255) DEFAULT NULL,
  `already_in_crm` tinyint(1) DEFAULT NULL,
  `review_status` varchar(50) DEFAULT NULL,
  `deny_reason` longtext DEFAULT NULL,
  `crm_record_id` varchar(100) DEFAULT NULL,
  `external_crm_url` varchar(500) DEFAULT NULL,
  `owner_rep` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `source` varchar(255) DEFAULT NULL,
  `scraping_method` varchar(20) DEFAULT NULL,
  `nurturing_stage` varchar(30) DEFAULT NULL,
  `pages_scraped` int(11) DEFAULT NULL,
  `last_scraped_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_17904552979B1AD6` (`company_id`),
  KEY `idx_leads_dupe` (`dupe_key`),
  KEY `idx_leads_region` (`region_tag`),
  KEY `idx_leads_score` (`lead_score`),
  KEY `idx_leads_website` (`website_root`),
  KEY `idx_leads_status` (`review_status`),
  KEY `idx_leads_created` (`created_at`),
  KEY `idx_leads_scraped` (`last_scraped_at`),
  KEY `idx_leads_nurturing` (`nurturing_stage`),
  CONSTRAINT `FK_17904552979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `learned_competitors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `domain` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `full_name` varchar(500) DEFAULT NULL,
  `tier` smallint(6) NOT NULL,
  `industry` varchar(50) NOT NULL,
  `discovery_source` varchar(50) NOT NULL,
  `discovery_context` longtext DEFAULT NULL,
  `detection_count` int(11) NOT NULL,
  `confidence_score` int(11) NOT NULL,
  `verified` tinyint(1) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `aliases` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`aliases`)),
  `keywords` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`keywords`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `first_detected_at` datetime NOT NULL,
  `last_detected_at` datetime NOT NULL,
  `verified_at` datetime DEFAULT NULL,
  `verified_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_learned_comp_domain` (`domain`),
  KEY `idx_learned_comp_tier` (`tier`),
  KEY `idx_learned_comp_active` (`active`),
  KEY `idx_learned_comp_verified` (`verified`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `meeting_slots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner_id` int(11) NOT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `meeting_type` varchar(50) NOT NULL,
  `duration_minutes` int(11) NOT NULL,
  `start_time` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `end_time` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `status` varchar(50) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  `meeting_url` varchar(500) DEFAULT NULL,
  `meeting_provider` varchar(50) DEFAULT NULL,
  `meeting_credentials` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meeting_credentials`)),
  `booked_by_name` varchar(255) DEFAULT NULL,
  `booked_by_email` varchar(255) DEFAULT NULL,
  `booked_by_phone` varchar(50) DEFAULT NULL,
  `booked_by_company` varchar(255) DEFAULT NULL,
  `booking_notes` longtext DEFAULT NULL,
  `booked_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `booking_token` varchar(100) DEFAULT NULL,
  `cancellation_token` varchar(100) DEFAULT NULL,
  `reminder_sent` tinyint(1) NOT NULL,
  `reminder_sent_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `confirmation_sent` tinyint(1) NOT NULL,
  `confirmation_sent_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `timezone` varchar(50) NOT NULL,
  `created_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `updated_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_A04577D0CE4B5C8E` (`booking_token`),
  KEY `IDX_A04577D07E3C61F9` (`owner_id`),
  KEY `IDX_A04577D0E7A1254A` (`contact_id`),
  KEY `IDX_A04577D0979B1AD6` (`company_id`),
  CONSTRAINT `FK_A04577D07E3C61F9` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_A04577D0979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_A04577D0E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notification` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `type` varchar(50) NOT NULL,
  `entity_type` varchar(50) NOT NULL,
  `entity_id` int(11) NOT NULL,
  `message` varchar(255) NOT NULL,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`data`)),
  `read_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_BF5476CAA76ED395` (`user_id`),
  KEY `idx_notification_user_read` (`user_id`,`read_at`),
  KEY `idx_notification_created` (`created_at`),
  CONSTRAINT `FK_BF5476CAA76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `nre_tables` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `service_type` varchar(100) NOT NULL,
  `flat_fee` decimal(15,4) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `asof` datetime NOT NULL,
  `version_id` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_service_type_asof` (`service_type`,`asof`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `onboarding_packs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `portal_candidate_id` int(11) DEFAULT NULL,
  `status` varchar(50) NOT NULL,
  `pack_contents` longtext DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `submitted_by` varchar(255) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `sha256_hash` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_846C0DCB979B1AD6` (`company_id`),
  KEY `IDX_846C0DCB91D286EE` (`portal_candidate_id`),
  KEY `idx_company_portal` (`company_id`,`portal_candidate_id`),
  CONSTRAINT `FK_846C0DCB91D286EE` FOREIGN KEY (`portal_candidate_id`) REFERENCES `portal_candidates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_846C0DCB979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `outbound_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contact_id` int(11) NOT NULL,
  `rfq_id` int(11) DEFAULT NULL,
  `subject_arm_id` int(11) DEFAULT NULL,
  `template_id` int(11) DEFAULT NULL,
  `subject` longtext NOT NULL,
  `body_text` longtext NOT NULL,
  `body_html` longtext DEFAULT NULL,
  `variation_hash` varchar(64) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `sent_at` datetime DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `opened_at` datetime DEFAULT NULL,
  `clicked_at` datetime DEFAULT NULL,
  `replied_at` datetime DEFAULT NULL,
  `message_id` varchar(255) DEFAULT NULL,
  `provider` varchar(50) DEFAULT NULL,
  `outcome_recorded` tinyint(1) NOT NULL DEFAULT 0,
  `recorded_event_type` varchar(20) DEFAULT NULL,
  `reply_classification` varchar(30) DEFAULT NULL,
  `reply_content` longtext DEFAULT NULL,
  `value_prop_arm_id` int(11) DEFAULT NULL,
  `tone_applied` varchar(30) DEFAULT NULL,
  `send_time_policy` varchar(50) DEFAULT NULL,
  `icp_cluster` varchar(100) DEFAULT NULL,
  `is_control_group` tinyint(1) NOT NULL DEFAULT 0,
  `decision_trace` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`decision_trace`)),
  `funnel_stage` varchar(20) NOT NULL DEFAULT 'pending',
  `reply_window_expiry` datetime DEFAULT NULL,
  `soft_failure_applied` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_642BA0C1ABD9545F` (`rfq_id`),
  KEY `IDX_642BA0C15DA0FB8` (`template_id`),
  KEY `idx_outbound_contact` (`contact_id`),
  KEY `idx_outbound_arm` (`subject_arm_id`),
  KEY `idx_outbound_status` (`status`),
  KEY `idx_outbound_sent` (`sent_at`),
  CONSTRAINT `FK_642BA0C1292D3428` FOREIGN KEY (`subject_arm_id`) REFERENCES `bandit_arms` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_642BA0C15DA0FB8` FOREIGN KEY (`template_id`) REFERENCES `spintax_templates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_642BA0C1E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_OBM_RFQ` FOREIGN KEY (`rfq_id`) REFERENCES `rfqs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `packaging_factors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(100) NOT NULL,
  `kg_per_unit` decimal(10,4) NOT NULL,
  `dm3_per_unit` decimal(10,4) NOT NULL,
  `palletization_rule_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`palletization_rule_json`)),
  `asof` datetime NOT NULL,
  `version_id` varchar(36) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category`),
  KEY `idx_asof` (`asof`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pcb_curves` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `layers` int(11) NOT NULL,
  `area_m2` decimal(12,2) NOT NULL,
  `cost_per_m2` decimal(15,4) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `asof` datetime NOT NULL,
  `version_id` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_layers_asof` (`layers`,`asof`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `personalization_archetypes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `archetype_name` varchar(100) NOT NULL,
  `description` longtext DEFAULT NULL,
  `target_industry` varchar(50) NOT NULL,
  `target_role` varchar(50) NOT NULL,
  `preferred_tone` varchar(50) NOT NULL,
  `preferred_content` varchar(50) NOT NULL,
  `preferred_style` varchar(50) NOT NULL,
  `feature_embedding` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`feature_embedding`)),
  `synthetic_engagement_score` int(11) NOT NULL DEFAULT 75,
  `topic_interests` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`topic_interests`)),
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_archetype_name` (`archetype_name`),
  KEY `idx_archetype_industry` (`target_industry`),
  KEY `idx_archetype_role` (`target_role`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `personalization_profiles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contact_id` int(11) DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `preferred_tone` varchar(50) NOT NULL,
  `preferred_content` varchar(50) NOT NULL,
  `preferred_style` varchar(50) NOT NULL,
  `topic_interests` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`topic_interests`)),
  `avoid_topics` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`avoid_topics`)),
  `feature_embedding` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`feature_embedding`)),
  `interaction_history` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`interaction_history`)),
  `emails_opened` int(11) NOT NULL,
  `emails_replied` int(11) NOT NULL,
  `emails_bounced` int(11) NOT NULL,
  `links_clicked` int(11) NOT NULL,
  `best_send_time` varchar(50) DEFAULT NULL,
  `best_send_day` varchar(10) DEFAULT NULL,
  `successful_subject_patterns` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`successful_subject_patterns`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_pers_contact` (`contact_id`),
  KEY `idx_pers_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `playbook_runs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `playbook_id` int(11) NOT NULL,
  `abm_hit_id` int(11) DEFAULT NULL,
  `triggered_at` datetime NOT NULL,
  `status` varchar(50) NOT NULL,
  `completed_at` datetime DEFAULT NULL,
  `execution_log` longtext DEFAULT NULL,
  `tasks_created` int(11) DEFAULT NULL,
  `error_message` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_7C70D89C2DB77442` (`playbook_id`),
  KEY `IDX_7C70D89C3C9131CC` (`abm_hit_id`),
  KEY `idx_playbook_abm_hit` (`playbook_id`,`abm_hit_id`),
  KEY `idx_playbook_runs_status` (`status`),
  CONSTRAINT `FK_7C70D89C2DB77442` FOREIGN KEY (`playbook_id`) REFERENCES `playbooks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_7C70D89C3C9131CC` FOREIGN KEY (`abm_hit_id`) REFERENCES `abm_hits` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `playbooks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `trigger_rules` longtext DEFAULT NULL,
  `actions` longtext DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL,
  `cooldown_hours` int(11) DEFAULT 24,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `portal_candidates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `portal_url` longtext NOT NULL,
  `status` varchar(50) NOT NULL,
  `discovered_at` datetime NOT NULL,
  `evidence_snapshot` longtext DEFAULT NULL,
  `has_robots_txt` tinyint(1) NOT NULL,
  `requires_manual_submit` tinyint(1) NOT NULL,
  `tos_url` longtext DEFAULT NULL,
  `tos_reviewed` tinyint(1) NOT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approved_by` varchar(255) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_DB6F19DA979B1AD6` (`company_id`),
  KEY `idx_company_status` (`company_id`,`status`),
  CONSTRAINT `FK_DB6F19DA979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `price_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote_id` int(11) DEFAULT NULL,
  `bom_line_id` int(11) DEFAULT NULL,
  `mpn` varchar(255) NOT NULL,
  `matched_mpn` varchar(255) DEFAULT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `source` varchar(50) NOT NULL,
  `unit_price` decimal(10,4) NOT NULL,
  `price_breaks` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`price_breaks`)),
  `currency` varchar(10) NOT NULL,
  `unit_price_usd` decimal(10,4) DEFAULT NULL,
  `stock_available` int(11) DEFAULT NULL,
  `lead_time_days` int(11) DEFAULT NULL,
  `lifecycle_status` varchar(50) DEFAULT NULL,
  `confidence_score` smallint(6) DEFAULT NULL,
  `confidence_level` varchar(20) DEFAULT NULL,
  `moq` int(11) DEFAULT NULL,
  `pack_quantity` int(11) DEFAULT NULL,
  `recorded_at` datetime NOT NULL,
  `raw_api_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`raw_api_response`)),
  PRIMARY KEY (`id`),
  KEY `IDX_4C9CB817DB805178` (`quote_id`),
  KEY `IDX_4C9CB817B2EEEC4D` (`bom_line_id`),
  KEY `idx_ph_mpn` (`mpn`),
  KEY `idx_ph_source` (`source`),
  KEY `idx_ph_date` (`recorded_at`),
  KEY `idx_ph_mpn_source` (`mpn`,`source`),
  CONSTRAINT `FK_PH_BOMLINE` FOREIGN KEY (`bom_line_id`) REFERENCES `bom_lines` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_PH_QUOTE` FOREIGN KEY (`quote_id`) REFERENCES `quotes` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `procurement_exception` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bom_line_id` int(11) NOT NULL,
  `exception_type` varchar(50) NOT NULL,
  `severity` varchar(20) NOT NULL,
  `message` longtext DEFAULT NULL,
  `recommendation` longtext DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_proc_exc_bomline` (`bom_line_id`),
  KEY `idx_proc_exc_severity` (`severity`),
  CONSTRAINT `FK_86428B89B2EEEC4D` FOREIGN KEY (`bom_line_id`) REFERENCES `bom_lines` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `quote_part_breakdowns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote_id` int(11) NOT NULL,
  `mpn` varchar(255) NOT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `unit_price` decimal(15,4) NOT NULL,
  `extended_price` decimal(15,2) NOT NULL,
  `data_source` varchar(100) DEFAULT NULL,
  `lead_time_days` int(11) DEFAULT NULL,
  `is_imputed` tinyint(1) NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_88D90569DB805178` (`quote_id`),
  CONSTRAINT `FK_88D90569DB805178` FOREIGN KEY (`quote_id`) REFERENCES `quotes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `quotes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `rfq_id` int(11) DEFAULT NULL,
  `quote_number` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL,
  `total_cost` decimal(15,2) NOT NULL,
  `currency` varchar(10) NOT NULL,
  `public_token` varchar(64) DEFAULT NULL,
  `token_expires_at` datetime DEFAULT NULL,
  `interactive_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `quantity_options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`quantity_options`)),
  `view_count` int(11) DEFAULT NULL,
  `last_viewed_at` datetime DEFAULT NULL,
  `coverage_percent` decimal(5,2) DEFAULT NULL,
  `alibaba_percent` decimal(5,2) DEFAULT NULL,
  `critical_dfm_count` int(11) DEFAULT NULL,
  `max_imputed_lead_time_days` int(11) DEFAULT NULL,
  `auto_published` tinyint(1) NOT NULL,
  `dataset_version_id` varchar(36) DEFAULT NULL,
  `api_versions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`api_versions`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `bom_data_json` longtext DEFAULT NULL,
  `ship_to_country` varchar(100) DEFAULT NULL,
  `incoterms` varchar(50) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `issuing_company` varchar(50) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_A1B588C5AC28B117` (`quote_number`),
  UNIQUE KEY `UNIQ_A1B588C5AE981E3B` (`public_token`),
  KEY `idx_company` (`company_id`),
  KEY `idx_quote_number` (`quote_number`),
  KEY `idx_status` (`status`),
  KEY `idx_public_token` (`public_token`),
  KEY `idx_quotes_contact` (`contact_id`),
  KEY `idx_quotes_rfq` (`rfq_id`),
  CONSTRAINT `FK_A1B588C5979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_A1B588C5ABD9545F` FOREIGN KEY (`rfq_id`) REFERENCES `rfqs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_A1B588C5E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `report_audits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `report_type` varchar(100) NOT NULL,
  `entity_type` varchar(100) NOT NULL,
  `entity_id` int(11) NOT NULL,
  `sha256_hash` varchar(64) NOT NULL,
  `version_id` varchar(100) DEFAULT NULL,
  `dataset_versions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`dataset_versions`)),
  `api_versions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`api_versions`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `generated_by` varchar(100) DEFAULT NULL,
  `generated_at` datetime NOT NULL,
  `notes` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_entity_type_id` (`entity_type`,`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `report_definitions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_by_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `report_type` varchar(50) NOT NULL,
  `data_source` varchar(50) NOT NULL,
  `columns` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`columns`)),
  `filters` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`filters`)),
  `group_by` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`group_by`)),
  `order_by` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`order_by`)),
  `chart_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`chart_config`)),
  `date_range_preset` varchar(50) DEFAULT NULL,
  `date_field` varchar(100) DEFAULT NULL,
  `custom_date_start` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `custom_date_end` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `record_limit` int(11) DEFAULT NULL,
  `is_public` tinyint(1) NOT NULL,
  `is_favorite` tinyint(1) NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  `access_roles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`access_roles`)),
  `scheduled_delivery` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`scheduled_delivery`)),
  `created_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `updated_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `last_run_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `run_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_22760ECAB03A8386` (`created_by_id`),
  CONSTRAINT `FK_22760ECAB03A8386` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rfq_line_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rfq_id` int(11) NOT NULL,
  `line_number` int(11) NOT NULL,
  `part_number` varchar(100) DEFAULT NULL,
  `customer_part_number` varchar(100) DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `quantity_annual` int(11) DEFAULT NULL,
  `quantity_per_batch` int(11) DEFAULT NULL,
  `unit_price` decimal(15,4) DEFAULT NULL,
  `nre_price` decimal(15,4) DEFAULT NULL,
  `currency` varchar(10) DEFAULT NULL,
  `lead_time_days` int(11) DEFAULT NULL,
  `technology` varchar(50) DEFAULT NULL,
  `component_count` int(11) DEFAULT NULL,
  `requires_xray` tinyint(1) NOT NULL DEFAULT 0,
  `requires_aoi` tinyint(1) NOT NULL DEFAULT 0,
  `requires_functional_test` tinyint(1) NOT NULL DEFAULT 0,
  `requires_conformal_coating` tinyint(1) NOT NULL DEFAULT 0,
  `specifications` longtext DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_DD15496DABD9545F` (`rfq_id`),
  CONSTRAINT `FK_DD15496DABD9545F` FOREIGN KEY (`rfq_id`) REFERENCES `rfqs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rfq_versions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rfq_id` int(11) NOT NULL,
  `version_number` int(11) NOT NULL,
  `revision_code` varchar(50) DEFAULT NULL,
  `revision_reason` longtext DEFAULT NULL,
  `status` varchar(50) NOT NULL,
  `estimated_value` decimal(15,2) DEFAULT NULL,
  `line_items_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`line_items_snapshot`)),
  `technical_scope` longtext DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `submitted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_C35B7AC5ABD9545F` (`rfq_id`),
  CONSTRAINT `FK_C35B7AC5ABD9545F` FOREIGN KEY (`rfq_id`) REFERENCES `rfqs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `rfqs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `lead_id` int(11) DEFAULT NULL,
  `rfq_number` varchar(100) DEFAULT NULL,
  `rfq_date` date DEFAULT NULL,
  `type` varchar(50) NOT NULL,
  `nda_sent` tinyint(1) NOT NULL DEFAULT 0,
  `nda_date` date DEFAULT NULL,
  `nda_executed` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(50) NOT NULL,
  `estimated_value` decimal(15,2) DEFAULT NULL,
  `currency` varchar(10) DEFAULT NULL,
  `volume_annual` int(11) DEFAULT NULL,
  `sop_date` date DEFAULT NULL,
  `technical_scope` longtext DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `loss_reason` varchar(50) DEFAULT NULL,
  `loss_reason_detail` longtext DEFAULT NULL,
  `competitor_won` varchar(255) DEFAULT NULL,
  `winning_bid_amount` decimal(15,2) DEFAULT NULL,
  `lessons_learned` longtext DEFAULT NULL,
  `win_factors` longtext DEFAULT NULL,
  `decision_date` date DEFAULT NULL,
  `award_date` date DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_530068A8979B1AD6` (`company_id`),
  KEY `IDX_530068A8E7A1254A` (`contact_id`),
  KEY `IDX_530068A855458D` (`lead_id`),
  CONSTRAINT `FK_530068A855458D` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_530068A8979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_BA4CF0F1E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `route_preferences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `destination_country` varchar(2) NOT NULL,
  `lane_code` varchar(100) NOT NULL,
  `rank` int(11) NOT NULL,
  `origin_port` varchar(100) DEFAULT NULL,
  `destination_port` varchar(100) DEFAULT NULL,
  `mode` varchar(50) NOT NULL,
  `weight_threshold_kg` decimal(10,2) DEFAULT NULL,
  `volume_threshold_m3` decimal(10,2) DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_destination_country` (`destination_country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sa_bayes_training` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `word` varchar(100) NOT NULL,
  `classification` varchar(30) NOT NULL,
  `frequency` int(11) NOT NULL DEFAULT 1,
  `last_updated` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_word_class` (`word`,`classification`),
  KEY `idx_bayes_classification` (`classification`),
  KEY `idx_bayes_word` (`word`)
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `spintax_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `template_type` varchar(50) NOT NULL DEFAULT 'email',
  `subject_spintax` longtext NOT NULL,
  `body_spintax` longtext NOT NULL,
  `available_variables` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`available_variables`)),
  `times_used` int(11) NOT NULL DEFAULT 0,
  `total_opens` int(11) NOT NULL DEFAULT 0,
  `total_replies` int(11) NOT NULL DEFAULT 0,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_spintax_type` (`template_type`),
  KEY `idx_spintax_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `supplier_portals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `registered` tinyint(1) NOT NULL DEFAULT 0,
  `registration_date` date DEFAULT NULL,
  `portal_username` varchar(255) DEFAULT NULL,
  `profile_completed` tinyint(1) NOT NULL DEFAULT 0,
  `notes` longtext DEFAULT NULL,
  `portal_url` varchar(500) DEFAULT NULL,
  `portal_id` varchar(255) DEFAULT NULL,
  `submitted_date` date DEFAULT NULL,
  `approval_date` date DEFAULT NULL,
  `buyer_name` varchar(255) DEFAULT NULL,
  `buyer_email` varchar(255) DEFAULT NULL,
  `buyer_contacted` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_27DDE79B979B1AD6` (`company_id`),
  CONSTRAINT `FK_27DDE79B979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tariff_rates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hs_code` varchar(20) NOT NULL,
  `origin_country` varchar(100) NOT NULL,
  `destination_country` varchar(100) NOT NULL,
  `duty_rate` decimal(5,2) NOT NULL,
  `mfn_rate` decimal(5,2) DEFAULT NULL,
  `fta_rate` decimal(5,2) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `expiry_date` date DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `fta_agreement` varchar(100) DEFAULT NULL,
  `version_id` varchar(36) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hs_code` (`hs_code`),
  KEY `idx_effective_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `assigned_to_id` int(11) DEFAULT NULL,
  `created_by_id` int(11) NOT NULL,
  `company_id` int(11) DEFAULT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `rfq_id` int(11) DEFAULT NULL,
  `lead_id` int(11) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `priority` varchar(20) NOT NULL,
  `type` varchar(20) NOT NULL,
  `due_date` date DEFAULT NULL,
  `due_time` time DEFAULT NULL,
  `estimated_minutes` int(11) DEFAULT NULL,
  `actual_minutes` int(11) DEFAULT NULL,
  `reminder_at` datetime DEFAULT NULL,
  `reminder_sent` tinyint(1) NOT NULL,
  `is_recurring` tinyint(1) NOT NULL,
  `recurring_frequency` varchar(20) DEFAULT NULL,
  `tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tags`)),
  `sort_order` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_50586597B03A8386` (`created_by_id`),
  KEY `IDX_50586597979B1AD6` (`company_id`),
  KEY `IDX_50586597E7A1254A` (`contact_id`),
  KEY `IDX_50586597ABD9545F` (`rfq_id`),
  KEY `IDX_5058659755458D` (`lead_id`),
  KEY `idx_task_status` (`status`),
  KEY `idx_task_due_date` (`due_date`),
  KEY `idx_task_assigned` (`assigned_to_id`),
  KEY `idx_task_priority` (`priority`),
  CONSTRAINT `FK_5058659755458D` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_50586597979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_50586597ABD9545F` FOREIGN KEY (`rfq_id`) REFERENCES `rfqs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_50586597B03A8386` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_50586597E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_50586597F4BD7827` FOREIGN KEY (`assigned_to_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(180) NOT NULL,
  `roles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`roles`)),
  `password` varchar(255) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `role` varchar(50) DEFAULT NULL,
  `territory` varchar(100) DEFAULT NULL,
  `active` tinyint(1) NOT NULL,
  `is_verified` tinyint(1) NOT NULL DEFAULT 0,
  `reset_token` varchar(100) DEFAULT NULL,
  `reset_token_expires_at` datetime DEFAULT NULL,
  `display_currency` varchar(10) DEFAULT NULL,
  `preferred_locale` varchar(10) DEFAULT NULL,
  `preferred_timezone` varchar(64) DEFAULT NULL,
  `preferred_theme` varchar(20) DEFAULT NULL,
  `accent_color` varchar(20) DEFAULT NULL,
  `font_size` varchar(20) DEFAULT NULL,
  `density` varchar(20) DEFAULT NULL,
  `reduced_motion` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_1483A5E9E7927C74` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `web_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp` datetime NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `url` longtext NOT NULL,
  `method` varchar(10) NOT NULL,
  `status_code` int(11) DEFAULT NULL,
  `user_agent` longtext DEFAULT NULL,
  `referer` longtext DEFAULT NULL,
  `is_processed` tinyint(1) NOT NULL,
  `processed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_timestamp_ip` (`timestamp`,`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `webinar_attendees` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `webinar_id` int(11) NOT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `registered_at` datetime NOT NULL,
  `attended` tinyint(1) NOT NULL DEFAULT 0,
  `follow_up_sent` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_webinar_email` (`webinar_id`,`email`),
  KEY `IDX_819128FAA391D86E` (`webinar_id`),
  KEY `IDX_819128FAE7A1254A` (`contact_id`),
  KEY `IDX_819128FA979B1AD6` (`company_id`),
  CONSTRAINT `FK_819128FA979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_819128FAA391D86E` FOREIGN KEY (`webinar_id`) REFERENCES `webinars` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_819128FAE7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `webinars` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `language` varchar(10) NOT NULL,
  `scheduled_date` datetime NOT NULL,
  `duration` int(11) NOT NULL,
  `description` longtext DEFAULT NULL,
  `registration_url` varchar(500) DEFAULT NULL,
  `recording_url` varchar(500) DEFAULT NULL,
  `meeting_url` varchar(500) DEFAULT NULL,
  `registered_count` int(11) NOT NULL DEFAULT 0,
  `attended_count` int(11) NOT NULL DEFAULT 0,
  `max_attendees` int(11) DEFAULT NULL,
  `status` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
