<?php

namespace App\Entity;

use App\Repository\CompetitorWatchlistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompetitorWatchlistRepository::class)]
#[ORM\Table(name: 'competitor_watchlists')]
#[ORM\HasLifecycleCallbacks]
class CompetitorWatchlist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $regionFilter = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $sectorFilter = null;

    #[ORM\Column(length: 60, nullable: true)]
    private ?string $competitorTypeFilter = null;

    #[ORM\Column(type: 'boolean', options: ['default' => true])]
    private bool $alertOnChange = true;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private bool $autoGenerated = false;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Competitor::class)]
    #[ORM\JoinTable(name: 'competitor_watchlist_members')]
    private Collection $competitors;

    public function __construct()
    {
        $this->competitors = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTime();
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTime();
    }

    public function getId(): ?int { return $this->id; }

    public function getName(): ?string { return $this->name; }
    public function setName(string $name): self { $this->name = $name; return $this; }

    public function getDescription(): ?string { return $this->description; }
    public function setDescription(?string $desc): self { $this->description = $desc; return $this; }

    public function getRegionFilter(): ?string { return $this->regionFilter; }
    public function setRegionFilter(?string $region): self { $this->regionFilter = $region; return $this; }

    public function getSectorFilter(): ?string { return $this->sectorFilter; }
    public function setSectorFilter(?string $sector): self { $this->sectorFilter = $sector; return $this; }

    public function getCompetitorTypeFilter(): ?string { return $this->competitorTypeFilter; }
    public function setCompetitorTypeFilter(?string $type): self { $this->competitorTypeFilter = $type; return $this; }

    public function isAlertOnChange(): bool { return $this->alertOnChange; }
    public function setAlertOnChange(bool $alert): self { $this->alertOnChange = $alert; return $this; }

    public function isAutoGenerated(): bool { return $this->autoGenerated; }
    public function setAutoGenerated(bool $auto): self { $this->autoGenerated = $auto; return $this; }

    public function getCreatedAt(): ?\DateTimeInterface { return $this->createdAt; }
    public function getUpdatedAt(): ?\DateTimeInterface { return $this->updatedAt; }

    /** @return Collection<int, Competitor> */
    public function getCompetitors(): Collection { return $this->competitors; }

    public function addCompetitor(Competitor $competitor): self
    {
        if (!$this->competitors->contains($competitor)) {
            $this->competitors->add($competitor);
        }
        return $this;
    }

    public function removeCompetitor(Competitor $competitor): self
    {
        $this->competitors->removeElement($competitor);
        return $this;
    }
}
